### ISSUE TITLE
New Live section

### ISSUE THREAD

**Issue by gunnartorfis** [gunnartorfis/gisk#16]
List out your leagues' participants' score predictions for the match that is currently live. 
We could even display all the matches for the current day in a similar way. It would probably at least be in the live section a bit after the match has ended so it wouldn't disappear straight after the scores have been updated. 

LEAGUE 1:
- User 1: 1 - 0
- User 2: 1 - 1

LEAGUE 2:
- User X: 1 - 1
- User Y: 2 - 1

**Comment by gunnartorfis** [comment]
@Siggnja gæti þetta ekki verið partur af #4?

**Comment by Siggnja** [comment]
Jú hugsa það
