### ISSUE TITLE
Indicate predicted matches

### ISSUE THREAD

**Issue by gunnartorfis** [gunnartorfis/gisk#2]
Users can only identify they have predicted a match from the numbers. 
0-0 result (the default one) doesn't indicate anything if the user wants to keep 0-0 as their prediction. 

Maybe a subtle green border around the number input? Or a yellow subtle one around untouched ones?

**Comment by birkirgr** [comment]
A addition to this could be an indication on how many points each played match returned the user. 
Would also help finding "next games", when more matches have been played and more scrolling is required. 


![Screenshot 2021-06-13 214826](https://user-images.githubusercontent.com/85842975/121822898-3b2c1100-cc91-11eb-97d9-12725a19089c.png)
