### ISSUE TITLE
Knockout matches should give more points

### ISSUE THREAD

**Issue by gunnartorfis** [gunnartorfis/gisk#25]
Only the semi-finals or finals? 2x? 1.5x? 
It should probably still be w.r.t. 90 minutes match, not extra time/penalties. 

Thoughts? @Siggnja

**Comment by Siggnja** [comment]
@gunnartorfis 
That a good idea, it would make things a lot more exciting. I say 1.5 and do it for the quarter-finals as well.

**Comment by gunnartorfis** [comment]
Fæ ég review á þessa?

https://github.com/gunnartorfis/gisk/pull/26
