### ISSUE TITLE
Default predictions

### ISSUE THREAD

**Issue by birkirgr** [gunnartorfis/gisk#28]
Default predictions should be blank - especially in knockout stage when 0-0 is a very valid prediction.
Games not predicted should not give points.

Know an example of a winner of a league, who did not make a single prediction in the knockout stage!!

**Comment by gunnartorfis** [comment]
I completely agree. 
It sounded better in my head before the tournament started, and I didn't want to alter the rules after the first match. 

I will definitely change this for the world cup. A random prediction generator button might come in handy for those who just want to play but don't have the time/knowledge to predict properly.
